### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kurddata2006** [inspireui/beonews#1]
<p>Hi , I got some errors  while open the  posts :<br> I use pro version .
attached images :<br>
<a href="http://www.hawalner.com/wp-content/uploads/2017/07/IMG_4327.png" rel="nofollow">Image 1</a><br>
<a href="http://www.hawalner.com/wp-content/uploads/2017/07/IMG_4328.png" rel="nofollow">Image 2</a><br>
<a href="http://www.hawalner.com/wp-content/uploads/2017/07/IMG_4329.png" rel="nofollow">Image 3</a><br></p><br>

**Comment by inspireui** [comment]
Hi, this could be cause by when viewing the post detail, could you share your URL to our support email support@inspireui.com then we will help to check your case, maybe we fix the Webview to support difference kind of content. Thank you!

**Comment by inspireui** [comment]
Closing this issue as fixed on v2.6. Please reopen it if you still have an issue. Thank you
