### ISSUE TITLE
my beonews installation problem video

### ISSUE THREAD

**Issue by pavilion016** [inspireui/beonews#10]
Hello, I made a video clip. My installation process and all the problems I received.

Step 1  I get error after run-ios command

React Native CFBundleidentifier does not exist

"https://www.youtube.com/watch?v=rewR1vWd3a8&feature=youtu.be"

then

to fix this problem I try command "react-native upgrade"   so project can build but get  next error 

"_reactNativeAdmob.AdmobInterstitial.setAdUnitID is undefined"

https://www.youtube.com/watch?v=roXF3S9lGzs&feature=youtu.be

now What do I do next?

**Comment by inspireui** [comment]
Hi, please try to fix the CFBundleidentifier  problem by download the  FacebookSDK (https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip) and copy to ~/Documents/FacebookSDK - https://beonews.inspireui.com/beonews-setup.html, don't try to use react-native upgrade as it will override the existing setting from the project.

**Comment by pavilion016** [comment]
I tried   you can see in my video 1

![chrome_2017-07-27_18-03-17](https://user-images.githubusercontent.com/291803/28667551-2c424162-72f6-11e7-882e-c7e87896ac17.png)

**Comment by inspireui** [comment]
Hi, please share your email to our support email support@inspireui.com then my technical guy will help  to resolve this issue on your mac, thank you!

**Comment by pavilion016** [comment]
resolve by clean install all
