### ISSUE TITLE
How to change BeoFoods text in title 

### ISSUE THREAD

**Issue by pavilion016** [inspireui/beonews#12]
How to change BeoFoods text in title

hello  can u give me solution or where file for change that , I check in language file it not in there.

and one more how I can change layout video list tap.

**Comment by inspireui** [comment]
Hi the BooFoods text is the logo image, you can replace the image to change it.

You can customize the list view of video to support the layout same as on the homepage.

**Comment by pavilion016** [comment]
I think i have some question


how to change splash screen  , I try in xcode but it still not change .


and if set facebook true it will be error when go to post page.

________________________________
จาก: InspireUI <notifications@github.com>
ส่ง: 13 สิงหาคม 2560 1:43:33
ถึง: inspireui/beonews
สำเนาถึง: pavilion016; Author
ชื่อเรื่อง: Re: [inspireui/beonews] How to change BeoFoods text in title (#12)


Hi the BooFoods text is the logo image, you can replace the image to change it.

You can customize the list view of video to support the layout same as on the homepage.

**Comment by inspireui** [comment]
Hi, you can change the splash screen from Xcode by change this storyboard - https://gyazo.com/16d81cb7c658ff7496d9bb5a341e1899
