### ISSUE TITLE
Red screen

### ISSUE THREAD

**Issue by e4mon** [inspireui/beonews#13]
![categories](https://user-images.githubusercontent.com/31044887/29328147-c159b558-821b-11e7-8bc5-48c1bff190e4.png)
![onclik sow red issue](https://user-images.githubusercontent.com/31044887/29328148-c15e5478-821b-11e7-8262-4c4b1de6dbc7.png)

By the way, minh did you check out my website?

**Comment by e4mon** [comment]
Most of the time I got this error " Null is not an object (evaluating 'data.better_featured_image['media_details])

**Comment by inspireui** [comment]
response via email, please check
