### ISSUE TITLE
onesignal push notification not open in app 

### ISSUE THREAD

**Issue by ashwithk4** [inspireui/beonews#18]
How to open a push notification by this app? I get push notifications from this app with OneSignal, but when I clicked the notifications, they were opened by default android browser. How to solve this?

**Comment by ashwithk4** [comment]
please reply the ticket i am waiting 2 more days

**Comment by inspireui** [comment]
Hi sorry for lated response as we are on the holiday. For the push notification it looks ok with my testing on both ios and android, so it could be the issues from your setting with the google account, please try to discover the detail document setting from - https://github.com/geektimecoil/react-native-onesignal (please note that the push notification will not work for the Expo version). Thank you!

**Comment by ashwithk4** [comment]
i have changed only one singal notification but its not open in app its open in android browser if you code working main also able to same work because i am not changed any code from the your bundle

**Comment by ashwithk4** [comment]
And also i am still not tried Expo version.

**Comment by ashwithk4** [comment]
Hi,


I have checked everything & got notification on your demo also.

Now I am find the error : when I am sending notifications or msg from
OneSignal dashboard its working on mobile app,

When we trying to update or publish post on WordPress, notification open in
mobile browser

**Comment by ashwithk4** [comment]
Hi,

I am resolved the above all issue, now i am getting notification & its working in app only. But when am click the notification its open app main screen instead of post.

**Comment by Careieste** [comment]
@ashwithk4  How did you resolved the notification opening in browser error?
Notifications sent from Wordpress always opens in web browser. How to fix it?

**Comment by ashwithk4** [comment]
Please read this

https://documentation.onesignal.com/v3.0/docs/wordpress
