### ISSUE TITLE
TabBar Navigation

### ISSUE THREAD

**Issue by Careieste** [inspireui/beonews#21]
1. When I set tabBarVisible: true on PostDetailScreen.js the Home icon is not visible. How to fix that?
2. How to set Video and Photos buttons to point to a specific category?
3. Please tell me how to fix this error:

Installing APK ‘app-debug.apk’ on ‘Samsung Galaxy S6 – 5.0.0 – API 21 – 1440×2560 – 5.0’ for app:debug Installed on 1 device.

BUILD SUCCESSFUL

Total time: 2 mins 52.911 secs Running C:\Android\sdk/platform-tools/adb -s 192.168.40.101:5555 reverse tcp:8081 tcp:8081 Starting the app on 192.168.40.101:5555 (C:\Android\sdk/platform-tools/adb -s 192.168.40.101:5555 shell am start -n com.beonews/com.beonews.MainActivity)... Starting: Intent { cmp=com.beonews/.MainActivity } 
Error type 3 Error: Activity class {com.beonews/com.beonews.MainActivity} does not exist.

Thank you!

**Comment by inspireui** [comment]
Hi, thank you for your questions: 

1. You can update the visible from the navigation/index.js, all the config the TabBar can be configured on this file.

2. Please refer to this screenshot – https://gyazo.com/ce5519253eb4b83fa0cd93b2e2dce271, example for the video you can can change the Config.CategoryVideo to any category id.

3. Looks like you have change the package name on Android that cause missing package issue, pls have a look to this #1 item – https://mstore.gitbooks.io/mstore-manual/content/chapter4.html (similar for beonews)
