### ISSUE TITLE
ios build error

### ISSUE THREAD

**Issue by Careieste** [inspireui/beonews#24]
1. ios app builded, but when starts on real iphone device after the splash screen it shows white screen and it remains white. Facebook id’s configured.  http://snag.gy/bDdfCX.jpg 

2. How to clean all 194 errors (yellow triangles)?  http://snag.gy/wO35RV.jpg

**Comment by inspireui** [comment]
fixed on latest version v.2.7. You could not clean up the yellow warning message as it still an issues from React Native framework. Thank you!
