### ISSUE TITLE
hi Error loading page  Domain:NSURLErrorDomain

### ISSUE THREAD

**Issue by ustczhangxg** [inspireui/beonews#25]
Error loading page  Domain:NSURLErrorDomain
http://www.kuoshao.com/2-11
2 Failed to load optimized model at path
http://www.kuoshao.com/1-18

**Comment by inspireui** [comment]
It looks like issue with your domain as it could not fetch the images, could you share your website URL here so that we can check the API. Thank you!

**Comment by ustczhangxg** [comment]
I didn't change the website url, it's still the http://news.inspireUI.com, and I think it may be caused by the second issue, Failed to load optimized model at path....http://www.kuoshao.com/1-18

**Comment by ustczhangxg** [comment]
http://www.kuoshao.com/3-6
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beonews.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by inspireui** [comment]
Hi, we have not used that URL from the demo DB, so it could caused by cached or the watchman config from your node server, please try with this script to clean cache and install the library - https://gist.github.com/inspireui/00e6f757c137b289c090173367c27af9
