### ISSUE TITLE
Help with installation!

### ISSUE THREAD

**Issue by mayolett** [inspireui/beonews#27]
Hi, I have sent a mail to you for help, you said you were going to you team viewer to help. kindly check

**Comment by Adamngooddad** [comment]
Need help with installing beonew 2.5 - pro  PLEASE!  ( BeoNews - React Native mobile app for Wordpress )  -  Item Purchase Code: f38d3637-39dc-465a-945c-2a65e48c288e

**Comment by mayolett** [comment]
hello, Can you please continue the help through teamviewer, I have been able to successfully run the app on genymotion, I just need help with wordpress integration

**Comment by inspireui** [comment]
@mayolett  @Adamngooddad  Please help to send the support request to our email if you still have the issue with the installing - support@inspireui.com. Thank you!
