### ISSUE TITLE
CFBundleIdentifier Does Not Exist

### ISSUE THREAD

**Issue by GrantRheingold** [inspireui/beonews#28]
Hi,

I have been unable to use the application as installing keeps resulting in this error:

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beonews.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

e.g., when I run the command "react-native run-ios", I get a lot of text while it's compiling. The final output lines however are:

CompileC /Users/grantrheingold/Desktop/BeoNews.2.7.1/beonews-pro/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/Objects-normal/x86_64/RCTFBSDKGraphRequestManager.o RCTFBSDK/core/RCTFBSDKGraphRequestManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/beonews.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beonews.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

I've tried "yarn install; yarn --reset-cache, and this does not work. 

Please help me fix this

**Comment by inspireui** [comment]
Hi, sorry for lated response as we have issue with the notify email.

Regarding to this issues please check 2 solution:
- Make sure your FacebookSDK is copied to the Documents folder, base on this guide - https://beonews.inspireui.com/beonews-setup.html

- If the above solution is not work please try this cmd:
`
yarn remove react-native-fbsdk
yarn install react-native-fbsdk
react-native react-native-fbsdk
`

Let me know your checking, thank you!

**Comment by spdnkt** [comment]
I am facing the same issue. Tried all available methods. Cannot use after purchase.. Please help fix it asap


The following build commands failed:

	PhaseScriptExecution Install\ Third\ Party /Users/spandankeot/Desktop/BeoNews.2.7.1/beonews-pro/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/beonews.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beonews.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by GrantRheingold** [comment]
Hi,

I tried running the commands above, in addition to already having gone through the setup process described. 

When I try to run the project in Xcode it still tells me "FBSDKCoreKit/FBSDKCoreKit.h file not found". This is just the error I see now - I'd imagine there could be more later. What else can I do to address this?

Spdnkt - as I understand it, the "CFBundleIdentifier" error can refer to a whole host of bugs/errors in the code, and it's just a sort of generic error that's thrown. To drill down into what's going on, it might help to open up Xcode and try building.

**Comment by inspireui** [comment]
Hi this is the common issue that missing dependencies libraries when build the app.

@GrantRheingold  For iOS, you need to download the FacebookSDK(https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip) and copy to ~/Documents/FacebookSDK as the guide on step 3. 

Please help to check this guide - https://beonews.inspireui.com/beonews-setup.html
