### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Adamngooddad** [inspireui/beonews#29]
Item Purchase Code: f38d3637-39dc-465a-945c-2a65e48c288e

Not getting the QR SCAN CODE that suppose to be at the bottom of the file

**Comment by Adamngooddad** [comment]
This is what I am getting

Item Purchase Code: f38d3637-39dc-465a-945c-2a65e48c288e
C:\Users\Richa\shoppingapp>npm install -g create-react-native-app
npm ERR! path C:\Users\Richa\AppData\Roaming\npm\create-react-native-app.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete C:\Users\Richa\AppData\Roaming\npm\create-react-native-app.cmd: is outside C:\Users\Richa\AppData\Roaming\npm\node_modules\create-react-native-app and not a link
npm ERR! File exists: C:\Users\Richa\AppData\Roaming\npm\create-react-native-app.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Richa\AppData\Roaming\npm-cache\_logs\2017-11-23T21_22_05_239Z-debug.log

C:\Users\Richa\shoppingapp>

**Comment by inspireui** [comment]
Hi please try to install the node to latest version will fixed the issue - http://nodejs.org

And try to make sure you have install all require library from this document - https://facebook.github.io/react-native/docs/getting-started.html 

Thank you!
