### ISSUE TITLE
Add image to category

### ISSUE THREAD

**Issue by peshwar9** [inspireui/beonews#3]
Hi in category list, right now only a list of rectangular boxes are shown with category title. How can I show images instead for categories? Tried adding image in Category component, but doesn't seem to work.

**Comment by minhcasi** [comment]
Hi, sorry, i've missed your comment, the image per category is disabled by performance issues, we will check to solution and update it soon on later version. Thank you!

**Comment by inspireui** [comment]
Hi, please try to add the image to the App/Common/Images.js file, the section: imageCategories (update the slug to match with your categories ID).

As the Wordpress is not support the category via Rest API so we need to update it as the static from the app, it mean you need to rebuild the app if want to add new category or change the image. It may not convenience but it help to speed up the app as don't need to request from the server.

Thank you for your feedback, please reopen the ticket if you still have an issue.

**Comment by peshwar9** [comment]
Hi- I downloaded latest version- 2.6-2.1. In the expo version, it works for your wp url. But if I use my url www.putttugam.com <http://www.putttugam.com/>, the data is fetched from backend but the main screen is not loaded (it shows the spinner continuously).
Can you check this out and let me know?

Thanks,
Prabhu

**Comment by inspireui** [comment]
Hi, i can not reach to your site - http://www.putttugam.com, could you check if it has already published
