### ISSUE TITLE
Issues with embedded instagram video

### ISSUE THREAD

**Issue by tayesho** [inspireui/beonews#31]
Hello,
My instgram videos aren't being loaded. I know I'm supposed to add a code to play Instagram videos to the videosourcereader.js but I don't know what to add. (I could be wrong).
https://imgur.com/IxhM6P3

Purchase Code: bda14e93-223a-42f7-897b-fe232d854bc9

**Comment by tayesho** [comment]
And also my category, videos & photos page are all empty

**Comment by tayesho** [comment]
why would you close the thread.
I've been waiting for days for an answer???

**Comment by inspireui** [comment]
Hi, sorry, we though we have processed the refund so that we close support.

Could you share your website URL here then we could have a check for instagram videos, if it is possible we can update on next version. Thank you!

**Comment by inspireui** [comment]
i'm closing this ticket as you have not response and could be have the solution - thank you
