### ISSUE TITLE
Image appears twice, Admob and signup doesnt appear.

### ISSUE THREAD

**Issue by mayolett** [inspireui/beonews#32]
Hi, after inserting an image once in a wordpress post, it is showing twice in the app, also admob is blank (I have changed the details in config.js. Finally signup and sign in doesn't appear. http://prntscr.com/hmwvt6 
http://prntscr.com/hmww4y

**Comment by inspireui** [comment]
HI @mayolett could you help to download the latest version v2.8.0 for fixing these issues- thank you!
