### ISSUE TITLE
Installation failing with error - cannot find entry file index.android.js react native

### ISSUE THREAD

**Issue by ksrc73** [inspireui/beonews#33]
Item Purchase Code: 3d0f768c-a3ff-45e8-9cad-ca8c70c8fccf

Initial installation is failing with following error for building android apk on a windows machine. Please help.
- cannot find entry file index.android.js react native

Tried multiple suggestions from stackoverflow regarding this error and all have not helped.
Added following line in android/app/build.gradle after renaming inndex.android.js to index.js
project.ext.react = [
    entryFile: "index.js"
]

**Comment by inspireui** [comment]
fixed on 2.8.1, it's now combine to one index.js file
