### ISSUE TITLE
Setting page black screen and font size problem

### ISSUE THREAD

**Issue by Careieste** [inspireui/beonews#34]
I have black screen on setting page and font size is not changed after I used the slider.
How to fix it on v2.8.0?
Thank you!
https://gyazo.com/dada38ff15610cff14b0b6467e34d205

**Comment by inspireui** [comment]
Hi, we will check the setting issue and get back to you soon with new fix. Thank you!

**Comment by inspireui** [comment]
fixed on 2.8.1
