### ISSUE TITLE
How do users exit the settings screen?

### ISSUE THREAD

**Issue by sungkhum** [inspireui/beonews#39]
I'm not sure how to exit the settings screen in the app on iOS? 
Also, is there a way to make it clear that the setting is to change the font size (like by saying "Choose a font size" before the slider?

Looks like there needs to be a back button or something?

![settings-screen](https://user-images.githubusercontent.com/1120218/34858679-89413bae-f706-11e7-804b-66a64c7fe24e.png)

**Comment by jambortamas** [comment]
@sungkhum in the issue #35 "the black setting screen will be fix on 2.8.1"

**Comment by sungkhum** [comment]
@jambortamas Ah, great - thank you!

**Comment by inspireui** [comment]
fixed on 2.8.1
