### ISSUE TITLE
Does not pull data from the my site.

### ISSUE THREAD

**Issue by kuantumm** [inspireui/beonews#4]
Hi.
Data comes in but application can not process. 
Apps Screenshot
![simulator screen shot 18 jul 2017 16 59 26](https://user-images.githubusercontent.com/21261708/28375694-d1efe6ba-6cb0-11e7-9c86-58afac81dbff.png)
Can you help me?
My site: [elazighakimiyet.com](url)

**Comment by inspireui** [comment]
Hi, please override this file from App/common folder - https://www.dropbox.com/s/j5htc645nqtwv01/Tools.js?dl=0, it will fix your issue. Thank you
