### ISSUE TITLE
Category page blank?

### ISSUE THREAD

**Issue by sungkhum** [inspireui/beonews#41]
Why is the category page blank until I click on the icon?
![category](https://user-images.githubusercontent.com/1120218/34898340-6f0a0ada-f7a7-11e7-8b86-aa41399d24e0.png)

**Comment by inspireui** [comment]
i'm not sure on this issue but we will investigate, thank you for your reporting issue.

**Comment by inspireui** [comment]
Hi @sungkhum thank you so much for your support in our ticket. Just update that all your report issues was fixed on v2.8.1 but we could not released on this week as there is an issue with latest react-native-fbsdk on Android, so we delay the release on early next week - very best.

**Comment by sungkhum** [comment]
Thanks - looking forward to it.

**Comment by inspireui** [comment]
fixed on 2.8.1
