### ISSUE TITLE
Need a clear back button on contact page

### ISSUE THREAD

**Issue by sungkhum** [inspireui/beonews#42]
This will make it easier for users.
Thanks!
![contact-no-back](https://user-images.githubusercontent.com/1120218/34898358-884547a8-f7a7-11e7-931b-bb84c3251115.png)

**Comment by inspireui** [comment]
yep, will we resolve this issue on next v2.8.1, this will be release on next week - thank you!

**Comment by inspireui** [comment]
fixed on 2.8.1
