### ISSUE TITLE
I am having issues while building default app.

### ISSUE THREAD

**Issue by umar-shafiq** [inspireui/beonews#45]
Hey, I am trying to setup the app but I am having some issues: 1. I am not able to build app on IOS and getting this error when I try to use command react-native run-ios

Error: Installing build/Build/Products/Debug-iphonesimulator/beonews.app An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2): lstat of /Users/umar/Desktop/Angular/app/code/beonews-pro/ios/build/Build/Products/Debug-iphonesimulator/beonews.app failed: No such file or directory No such file or directory Print: Entry, ”:CFBundleIdentifier, Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beonews.app/Info.plist Print: Entry,”, Does Not Exist

Secondly on Android: 
1. When open the app first time it shows blank page without any content. Than when I pull down the screen it shows the content.
https://i.imgur.com/koDCKij.png

2. The app is not fetching any of my categories. It just load some content when I use the button on the app page.
https://i.imgur.com/Iy6v94Y.png

3. Videos are not working and giving long error on red screen.
https://i.imgur.com/j0kXK4u.png

4. Also how to setup readlaterTable table in firebase. There is no documentation available for that.

**Comment by sungkhum** [comment]
@cr3atives  See here and see if that helps with the Xcode build error: https://github.com/inspireui/beonews/issues/28

**Comment by umar-shafiq** [comment]
@sungkhum Doesn't not solve the problem with Xcode build error tried both solutioins.

**Comment by inspireui** [comment]
@cr3atives could you share your screenshot detail log issue when build with XCode ?

Please make sure to update the config for HorizonLayout and CategoryVideo id to fix the issue #1, #2, #3 - if you have done these config - please share it here then we could have a check.

This is document for #4 - https://beonews.inspireui.com/step-4-firebase-config.html

**Comment by umar-shafiq** [comment]
@inspireui Can you please lead to document how can I create structure like this in firebase.
https://beonews.inspireui.com/assets/Screen%20Shot%202017-01-08%20at%205.04.57%20PM.png

or atleast table list_readlater. I wanted to make sure that offline data from the app is getting stored in firebase.

**Comment by umar-shafiq** [comment]
@inspireui Can i get your skype? I need to get this app working today, Thanks

Also now the app is build succeeded in ios but crash right after launch. Please check the video below for the issues I am facing.

https://www.screencast.com/t/p0xO3gJ4Sxy

you need get flash player to play video.

**Comment by umar-shafiq** [comment]
@inspireui ??

**Comment by inspireui** [comment]
Hi @cr3atives can you send the request to our support email: support@inspireui.com then our technical will give directly support - thanks

**Comment by inspireui** [comment]
resolved
