### ISSUE TITLE
Sugestions for v2.8.1

### ISSUE THREAD

**Issue by Careieste** [inspireui/beonews#46]
1. Option to Disable screen turn off while using the app.
2. Make possible to bookmark sections of text, not just the entire article. Also make possible to share sections of text (selected text from an article).
3. Make possible to change Photos button with another article category.
4. Make possible to add audio.
5. Make possible to add live video.
6. Fix change text size.
Thank you!

**Comment by inspireui** [comment]
Thank you for your suggestion, we will investigate and have a change logs if fixed these issues.

**Comment by imnews** [comment]
Can you make language switch function?thx

**Comment by imnews** [comment]
[shortcode] can you make possible?
