### ISSUE TITLE
where is the information for a basic customisation

### ISSUE THREAD

**Issue by fsonmez** [inspireui/beonews#47]
I see there are no information at all for the basic customisation of the project, for example;

how to change layouts on home page or hide spesific layouts maybe, which line and file?
how to change menu structure, the menu items, names?
where to set categories?

should we have to try and see for these, simple instructions about these would help a lot..

**Comment by sungkhum** [comment]
@fsonmez You'll find the answers to most of your questions in the documentation: https://beonews.inspireui.com/test2.html

Changing the layout isn't all that easy for those who do not have experience, but you can comment out specific layouts (for example remove the video section by commenting out the const videoStack lines in index.js in App/Navigation)
Change item names here: https://beonews.inspireui.com/step-7-multi-languages.html
And you set categories in App/Common/Config.js

Hope that helps some.
