### ISSUE TITLE
Error opening project on Expo XDE

### ISSUE THREAD

**Issue by designrootstudio** [inspireui/beonews#49]
Hi,
I'm trying to open the project on Expo XDE but there is an error with version of Expo (SDK 17.0.0).
Which is the correct version? Where is the problem..

Attachment screenshot,
thank you

![captura de pantalla 2018-01-22 a las 19 42 10](https://user-images.githubusercontent.com/35607596/35237949-5561a13a-ffac-11e7-9921-8c54cce203a0.png)

**Comment by inspireui** [comment]
<img width="466" alt="screen shot 2018-01-24 at 3 13 37 pm" src="https://user-images.githubusercontent.com/29778334/35321223-2f8f4a52-0119-11e8-89c3-eecbebde5a8b.png">

Hi try to change host to **Lan** and Protocol to **exp** will fix the issue

**Comment by designrootstudio** [comment]
Hi, 
it still doesn't work..

- macOS ^10
- Node v08.9.4
- Expo XDE 2.22

When I'm installing `yarn`, there is next error..

error https://github.com/callstack-io/react-native-fbads/tarball/v4.1.0: Fetch succeeded for undefined. However, extracting "https://github.com/callstack-io/react-native-fbads/tarball/v4.1.0" resulted in hash "e59aae9c953fff175dd617df5acc58a8e71a211e", which did not match the requested hash "e836ed7f4502593d4a4757f27cdfa0ffef4dc729".

I follow the guide but I can't run the project..

<img width="1611" alt="captura de pantalla 2018-01-24 a las 18 55 08" src="https://user-images.githubusercontent.com/35607596/35350822-60db59fe-013f-11e8-96ac-cf423267921e.png">

**Comment by designrootstudio** [comment]
Please, can I get your Skype?
I need to get this app working next week,
Thanks

**Comment by inspireui** [comment]
hi, pls try to send the request to our support email: suppor@insipreui.com - also share your purchased code  - thank you!

**Comment by inspireui** [comment]
Hi, please update the latest version and Expo version, let me know if you still have an issue - thank you!

**Comment by designrootstudio** [comment]
Hi,
Yes, it's run ok! Thank you so much
---- Original Message ----
