### ISSUE TITLE
Easiest Way to Upgrade?

### ISSUE THREAD

**Issue by sungkhum** [inspireui/beonews#50]
What's the easiest way to upgrade from 2.8.0 to 2.8.1 (and any version in the future?)?
Better to start from scratch or is there a way to merge?

**Comment by inspireui** [comment]
Hi @sungkhum you can use the git repo to override the new version to the modify changed from the history, you can use from git UI tool like Source Tree

Btw, most of change from the components and library so it could not impact to the business logic :)
