### ISSUE TITLE
Slider Does not Appear and Push notifications not working.

### ISSUE THREAD

**Issue by ismetertekin** [inspireui/beonews#51]
Hi,
I have some problems.
- The slider does not appear when the view changes. I want to use a full screen slider. As in the demo application.
- I could not run the notifications. I created a new application onesignal. I created Apple Push Notification service SSL (Sandbox & Production) certification from the IOS developer console.After uploading this certificate I exported it in p12 format.I activated iOSignal with .p12 extension certificate.I archived the application and installed it on the real device.I sent a test notification from the Onesignal console, but did not come to the phone.
- How do I remove the clock that appears under the text? Example 3 hours ago.Or how can I show the category name instead of the time?
- How do I change the left menu type?
- How can I turn off the option of popping up the labels on the popup screen. Only categories are enough.

When the screen changes, do not come on the slider screen video link below.
http://www9.zippyshare.com/v/iX0CPCkq/file.html

King Regards,

**Comment by inspireui** [comment]
Hi please read more detail guide from this library could be help to find out your push notification issues - https://github.com/geektimecoil/react-native-onesignal

Regarding to the slider, please update the style on banner image or update the image size.

Please sympathize  for kind of customization question as we could not answer them all, we only give suggestion for the installing issue. Please help to discover more the React native language.

**Comment by ismetertekin** [comment]
Hello there,
I took care of a lot of my questions myself.
But I want to make a suggestion. Maybe in the new version.
Clicking the notification opens the website in the application. It would be nice to open the news detail in practice instead.
Thanks.

**Comment by inspireui** [comment]
Thank you for your suggestion, we will check the solution when click to show deep link from the notification
