### ISSUE TITLE
Logo alignment

### ISSUE THREAD

**Issue by Careieste** [inspireui/beonews#56]
Why the logo is not on the same line as the menu icon?
https://gyazo.com/54791bc3ae59f0a875db43d163a17b05

**Comment by sungkhum** [comment]
Yeah, I haven't figured out how to customize the logo position either. I would be interested in knowing how to do this as well.

**Comment by inspireui** [comment]
Hi, it kind of new design from the app :) 

You can replace or customize the the AnimateHeader component to update these UI.

**Comment by sungkhum** [comment]
@inspireui I searched for AnimateHeader in all the files but cannot find it. Where it is located?

**Comment by inspireui** [comment]
@sungkhum it from App/Components/AnimatedHeader/
