### ISSUE TITLE
Some content holder styled bad 

### ISSUE THREAD

**Issue by kurddata2006** [inspireui/beonews#6]
Hi , Thanks for very goog update , just two question :some place holder in RTL mode dosen’t good styled and need more attention for RTL , How can I fix them, I take same screenshot for you , The website who connected to app is [www.hawalner.com](http://www.hawalner.com)
[Post content dosen’t aligned right 
](http://www.hawalner.com/wp-content/uploads/2017/07/IMG_4410.png)[Post title in List view mode ](http://www.hawalner.com/wp-content/uploads/2017/07/IMG_4410.png)
[liked posts (saved posts) lists not aligned right and cropped](http://www.hawalner.com/wp-content/uploads/2017/07/IMG_4413.png)
Please help me to customise better , your app is perfect , thanks again .

**Comment by inspireui** [comment]
Hi, we will update the RTL issue on next version. Thank you!

**Comment by inspireui** [comment]
fixed on latest version v.2.7.0.  Thank you!
