### ISSUE TITLE
Font Size inside tag html

### ISSUE THREAD

**Issue by aidlsantoso76** [inspireui/beonews#62]
Font size include tag from API on post can't change.

from API: `<p>This is <strong>NICE</strong> template. I <em>LIKE</em> it</p>`

word "NICE" and "LIKE" not changed after setting content font size.

**Comment by inspireui** [comment]
Hi, you can go to Component/Webview/index.js and add strong, em to tagsStyles properties:

const tagsStyles = {
      a: {color: '#333', fontSize: fontSize},
      p: {color: '#333', fontSize: fontSize},
      em:  {color: '#333', fontSize: fontSize},
      strong:  {color: '#333', fontSize: fontSize},
      img: {resizeMode: 'cover'}
    }
