### ISSUE TITLE
How to disable some items in the tabbar and in the left menu?

### ISSUE THREAD

**Issue by amingomezd** [inspireui/beonews#63]
Hi, i have not completed customizing the app and i plan to launch in the play store the first version of the app without the Videos and Photos, how can i disable the icons in the tabbar? @inspireui

**Comment by amingomezd** [comment]
solved, you have to comment out the section you don't want to show in app/navigation/index.js, ie: 
`photo: {screen: PhotoScreen},`
and it won't show the photos section, and rearrange the tabbar.

I wanted to disable the photo screen because it doesn't work correctly, you can't drag the photos to see them all, so it's useless.

**Comment by inspireui** [comment]
Thank you for resolving it quickly :)
