### ISSUE TITLE
Internal Link not work

### ISSUE THREAD

**Issue by tohaitrieu** [inspireui/beonews#7]
Dear Support
When I insert a post to my another post and click in app, it does not work and give red screen.

Invalid URL: should be a string. Was: undefined

_validateURL
    Linking.js:216:6
canOpenURL
    Linking.js:200:22
externalLink
    index.js:21:23
onLinkPress
    index.js:63:54
onPress
    HTMLRenderers.js:27:84
touchableHandlePress
    Text.js:295:57
_performSideEffectsForTransition
    Touchable.js:746:34
_receiveSignal
    Touchable.js:664:44
touchableHandleResponderRelease
    Touchable.js:433:24
<unknown>
    Text.js:325:49
invokeGuardedCallback
    ReactNativeStack-dev.js:134:19
invokeGuardedCallbackAndCatchFirstError
    ReactNativeStack-dev.js:173:64
executeDispatch
    ReactNativeStack-dev.js:206:128
executeDispatchesInOrder
    ReactNativeStack-dev.js:212:279
executeDispatchesAndRelease
    ReactNativeStack-dev.js:276:58
forEachAccumulated
    ReactNativeStack-dev.js:272:37
processEventQueue
    ReactNativeStack-dev.js:344:143
runEventQueueInBatch
    ReactNativeStack-dev.js:641:79
handleTopLevel
    ReactNativeStack-dev.js:646:29
<unknown>
    ReactNativeStack-dev.js:753:51
perform
    ReactNativeStack-dev.js:1391:99
batchedUpdatesWithControlledComponents
    ReactNativeStack-dev.js:712:30
_receiveRootNodeIDEvent
    ReactNativeStack-dev.js:752:46
receiveTouches
    ReactNativeStack-dev.js:766:60
__callFunction
    MessageQueue.js:260:47
<unknown>
    MessageQueue.js:101:26
__guard
    MessageQueue.js:228:6
callFunctionReturnFlushedQueue
    MessageQueue.js:100:17

**Comment by inspireui** [comment]
Thanks Trieu, we are checking this internal link issue

**Comment by inspireui** [comment]
fixed on latest version v2.7.0
