### ISSUE TITLE
Custom CSS Webview.

### ISSUE THREAD

**Issue by tohaitrieu** [inspireui/beonews#8]
Hi Support

In PostDetail, i saw you use WebView to render html from post.

  <WebView html={postContent} />

I want to custom css as paragraph padding, margin and some class css.

How to i custom it?

Thanks.

**Comment by inspireui** [comment]
Hi, you can customize it from the Components/Webview/index.js file - https://gyazo.com/a28c55dfcba92185281243cf4824ca08
